version: '3.9'
services:
    # nginx:
    #     build:
    #         dockerfile: ./nginx/Dockerfile
    #     depends_on:
    #         - app
    #     ports:
    #         - "127.0.0.1:5100:5100"
    #     restart: always
    app:
        build:
            dockerfile: ./service/Dockerfile
        restart: always
        deploy:
            replicas: 4
        volumes:
            - ./stdout.log:/stdout.log
    sleeping_app:
        build:
            dockerfile: ./sleeping_service/Dockerfile
        restart: always
        deploy:
            replicas: 1
        volumes:
            - ./stdout.log:/stdout.log
    proxy:
        build:
            dockerfile: ./proxy_server/Dockerfile
        depends_on:
            - app
        ports:
            - "127.0.0.1:5100:5100"
        restart: always
        links:
            - src-sleeping_app-1
            - src-app-1
            - src-app-2
            - src-app-3
            - src-app-4